create extension if not exists pgcrypto;
create type public.school_role as enum ('Student','Representative','Owner');
create table public.profiles(id uuid primary key references auth.users on delete cascade,name text not null default '' check(length(name)<=120),email text not null,active boolean not null default true,created_at timestamptz not null default now());
create table public.user_roles(user_id uuid primary key references public.profiles on delete cascade,role public.school_role not null default 'Student');
create unique index sole_owner on public.user_roles(role) where role='Owner';
create table public.categories(id uuid primary key default gen_random_uuid(),name text not null unique check(length(name) between 1 and 80),color text not null default '#227869' check(color ~ '^#[0-9a-fA-F]{6}$'));
create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null unique check(length(name) between 1 and 120),description text not null default '',created_at timestamptz not null default now());
create table public.organization_representatives(user_id uuid references public.profiles on delete cascade,organization_id uuid references public.organizations on delete cascade,primary key(user_id,organization_id));
create index assignment_org on public.organization_representatives(organization_id);
create table public.events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations on delete restrict,category_id uuid not null references public.categories on delete restrict,title text not null check(length(trim(title)) between 1 and 180),description text not null default '',starts_at timestamptz not null,ends_at timestamptz not null,all_day boolean not null default false,location text not null default '',external_url text not null default '' check(external_url='' or external_url ~ '^https?://'),status text not null default 'draft' check(status in ('draft','published')),created_by uuid not null references public.profiles,updated_by uuid not null references public.profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at>=starts_at));
create index events_start on public.events(starts_at);
create index events_org on public.events(organization_id,starts_at);
create index events_category on public.events(category_id,starts_at);
create table public.favorites(user_id uuid references public.profiles on delete cascade,event_id uuid references public.events on delete cascade,primary key(user_id,event_id));
create index favorites_event on public.favorites(event_id);
create table public.settings(id boolean primary key default true check(id),school_name text not null default 'SchoolCentral',timezone text not null default 'America/Toronto');
insert into public.settings default values;
create function public.is_active() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and active)$$;
create function public.is_owner() returns boolean language sql stable security definer set search_path='' as $$select public.is_active() and exists(select 1 from public.user_roles where user_id=auth.uid() and role='Owner')$$;
create function public.can_manage(org uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_owner() or (public.is_active() and exists(select 1 from public.user_roles r join public.organization_representatives a on a.user_id=r.user_id where r.user_id=auth.uid() and r.role='Representative' and a.organization_id=org))$$;
create function public.new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,name,email) values(new.id,left(coalesce(new.raw_user_meta_data->>'name','Student'),120),new.email);insert into public.user_roles(user_id) values(new.id);return new;end$$;
create trigger new_user after insert on auth.users for each row execute function public.new_user();
create function public.event_audit() returns trigger language plpgsql set search_path='' as $$begin if TG_OP='INSERT' then new.created_by=auth.uid();new.created_at=now();else new.created_by=old.created_by;new.created_at=old.created_at;end if;new.updated_by=auth.uid();new.updated_at=now();return new;end$$;
create trigger event_audit before insert or update on public.events for each row execute function public.event_audit();
create function public.assign_representative(target uuid,orgs uuid[]) returns void language plpgsql security definer set search_path='' as $$begin if not public.is_owner() then raise exception 'Owner required';end if;if exists(select 1 from public.user_roles where user_id=target and role='Owner') then raise exception 'Cannot modify Owner';end if;if not exists(select 1 from public.profiles where id=target and active) then raise exception 'Active user required';end if;update public.user_roles set role=case when cardinality(orgs)>0 then 'Representative'::public.school_role else 'Student'::public.school_role end where user_id=target;delete from public.organization_representatives where user_id=target;insert into public.organization_representatives(user_id,organization_id) select target,unnest(orgs);end$$;
create function public.protect_owner() returns trigger language plpgsql set search_path='' as $$begin if exists(select 1 from public.user_roles where user_id=old.id and role='Owner') and not new.active then raise exception 'Owner cannot be disabled';end if;return new;end$$;
create trigger protect_owner before update on public.profiles for each row execute function public.protect_owner();
alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.categories enable row level security;
alter table public.organizations enable row level security;
alter table public.organization_representatives enable row level security;
alter table public.events enable row level security;
alter table public.favorites enable row level security;
alter table public.settings enable row level security;
create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or public.is_owner());
create policy profiles_owner_update on public.profiles for update to authenticated using(public.is_owner()) with check(public.is_owner());
create policy roles_read on public.user_roles for select to authenticated using(user_id=auth.uid() or public.is_owner());
create policy assignments_read on public.organization_representatives for select to authenticated using(user_id=auth.uid() or public.is_owner());
create policy organizations_read on public.organizations for select to authenticated using(public.is_active());
create policy organizations_owner on public.organizations for all to authenticated using(public.is_owner()) with check(public.is_owner());
create policy categories_read on public.categories for select to authenticated using(public.is_active());
create policy categories_owner on public.categories for all to authenticated using(public.is_owner()) with check(public.is_owner());
create policy events_read on public.events for select to authenticated using(public.is_active() and (status='published' or public.can_manage(organization_id)));
create policy events_insert on public.events for insert to authenticated with check(public.can_manage(organization_id));
create policy events_update on public.events for update to authenticated using(public.can_manage(organization_id)) with check(public.can_manage(organization_id));
create policy events_delete on public.events for delete to authenticated using(public.can_manage(organization_id));
create policy favorites_read on public.favorites for select to authenticated using(public.is_active() and user_id=auth.uid());
create policy favorites_insert on public.favorites for insert to authenticated with check(public.is_active() and user_id=auth.uid() and exists(select 1 from public.events where id=event_id and status='published'));
create policy favorites_delete on public.favorites for delete to authenticated using(user_id=auth.uid());
create policy settings_read on public.settings for select to authenticated using(public.is_active());
create policy settings_owner on public.settings for update to authenticated using(public.is_owner()) with check(public.is_owner());
revoke all on public.profiles,public.user_roles,public.organization_representatives,public.events,public.categories,public.organizations,public.favorites,public.settings from anon,authenticated;
grant select on public.profiles,public.user_roles,public.organization_representatives,public.settings to authenticated;
grant update(name,active) on public.profiles to authenticated;
grant update(school_name,timezone) on public.settings to authenticated;
grant select,insert,update,delete on public.events,public.categories,public.organizations,public.favorites to authenticated;
revoke all on function public.assign_representative(uuid,uuid[]),public.new_user(),public.event_audit(),public.protect_owner(),public.is_active(),public.is_owner(),public.can_manage(uuid) from public;
grant execute on function public.assign_representative(uuid,uuid[]),public.is_active(),public.is_owner(),public.can_manage(uuid) to authenticated;
-- Realtime sends only rows visible under SELECT RLS. Refresh fallback handles deletes.
alter publication supabase_realtime add table public.events;

