import 'server-only';
import {createClient} from '@supabase/supabase-js';
import {createHash,randomBytes} from 'node:crypto';
export const hashToken=(token:string)=>createHash('sha256').update(token).digest('hex');
export function adminClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw Error('Application email service is not configured.');return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
export function siteUrl(){const raw=process.env.SITE_URL;if(!raw)throw Error('SITE_URL is not configured.');const url=new URL(raw);if(url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw Error('SITE_URL must use HTTPS.');return url.origin;}
export async function authenticatedClient(request:Request){const authorization=request.headers.get('authorization')||'';if(!authorization.startsWith('Bearer '))throw Error('Sign in first.');const client=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await client.auth.getUser(authorization.slice(7));if(error||!data.user)throw Error('Sign in first.');return client;}
export function mailConfigured(){if(!process.env.RESEND_API_KEY||!process.env.EMAIL_FROM)throw Error('Email delivery is not configured.');siteUrl();}
export async function sendMail(to:string,subject:string,text:string,idempotency:string){mailConfigured();const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':idempotency},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[to],subject,text})});if(!response.ok)throw Error('Email could not be delivered. Please retry.');}
export async function sendTeacherEmail(applicationId:string){const admin=adminClient();const {data:application,error}=await admin.from('representative_applications').select('*').eq('id',applicationId).single();if(error||!application||application.status!=='pending_teacher')throw Error('Application is unavailable.');const {data:teacher}=await admin.from('approved_teachers').select('email').eq('email',application.teacher_email).maybeSingle();if(!teacher)throw Error('Teacher is no longer authorized.');const {data:reserved,error:reserveError}=await admin.rpc('reserve_teacher_email',{application:application.id});if(reserveError||!reserved)throw Error('Wait five minutes before requesting another email.');const token=randomBytes(32).toString('hex'),now=Date.now();const {error:tokenError}=await admin.from('teacher_approval_tokens').upsert({application_id:application.id,token_hash:hashToken(token),expires_at:new Date(now+48*3600000).toISOString(),used_at:null,last_sent_at:new Date(now).toISOString()});if(tokenError)throw Error('Could not prepare teacher approval.');const link=`${siteUrl()}/teacher-review#token=${token}`;try{await sendMail(application.teacher_email,'SchoolCentral: representative application for your review',`${application.applicant_name} has applied to represent ${application.club_name}.\n\n${application.description}\n\nReview and approve or decline this application:\n${link}\n\nThis link expires in 48 hours and can be used once. Do not forward it. Opening it does not approve the request. The Owner must also approve before access is granted.`,`${application.id}:${hashToken(token)}`)}catch(e){await admin.from('teacher_approval_tokens').delete().eq('application_id',application.id).eq('token_hash',hashToken(token));throw e;}}
export async function sendOwnerNotifications(){const admin=adminClient();const {data:role,error:roleError}=await admin.from('user_roles').select('user_id').eq('role','Owner').single();if(roleError||!role)throw Error('Owner account is not configured.');const {data:identity,error:identityError}=await admin.auth.admin.getUserById(role.user_id);if(identityError||!identity.user?.email)throw Error('Owner email is unavailable.');const {data:pending,error}=await admin.from('application_notification_outbox').select('application_id').is('sent_at',null).limit(10);if(error)throw Error('Notification queue is unavailable.');for(const item of pending||[]){const {data:application}=await admin.from('representative_applications').select('club_name,applicant_name').eq('id',item.application_id).single();if(!application)continue;await sendMail(identity.user.email,'SchoolCentral: teacher-approved application awaits you',`${application.applicant_name}'s application for ${application.club_name} has been approved by their teacher.\n\nSign in to SchoolCentral and open Owner dashboard → Applications to approve or decline it.\n${siteUrl()}`,`owner-application:${item.application_id}`);const {error:markError}=await admin.from('application_notification_outbox').update({sent_at:new Date().toISOString()}).eq('application_id',item.application_id);if(markError)throw Error('Could not record notification delivery.');}}
